
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoxgpdtrszswnpilkzma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVveGdwZHRyc3pzd25waWxrem1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzMzNjIsImV4cCI6MjA2MzMwOTM2Mn0.C_si0YkeXKs9WguqOwCa291Lbg_1Fp4VKIHq8aRJ1nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
